### PR TITLE
New domains

### PR DESCRIPTION
**Pull request by tierpod**
* Add support .ua (.com.ua)
* Fix support .kg

### CODE REVIEW

**Comment by k0ste** [comment]
Thanks.

**Comment by tierpod** [comment]
You are welcome. Can you upload updated version to pypi?

**Comment by k0ste** [comment]
@gen1us2k can.

**Comment by gen1us2k** [comment]
Version updated. @tierpod. BTW you can be contributor of this project if you want. Also I'm going to move this project to my company profile and add one another one contributor for this project. This project needs refactoring and more support.

**Comment by tierpod** [comment]
@gen1us2k Thank you for offer. I has no experience in contributing and I will try with pleasure. And it will be a good practice in python. My current interest is monitoring expiration time for domains.

PS. I found another project https://bitbucket.org/richardpenman/pywhois which already looks like refactored original python-whois project.

**Pull request merged**
