### PR TITLE
Add travel domain; strip each name server string

### PR DESCRIPTION
**Pull request by tierpod**
* Add regexps for "travel" domain
* I have found some cases when name servers contains "\r" symbol at the end, so I've added strip() to every name server.

### CODE REVIEW

**Comment by k0ste** [comment]
> I have found some cases when name servers contains "\r" symbol at the end, so I've added strip() to every name server.

Can you provide reproducer? Maybe some domain.
Thanks.

**Comment by tierpod** [comment]
Of course, without 18cdcc7 commit:

```
$ python2 test.py google.org
--------------------------------------------------------------------------------
Domain: google.org, host: None
        last_updated	"2019-09-18 09:31:16"
                name	"google.org"
       registrant_cc	"us"
       creation_date	"1998-10-21 04:00:00"
           registrar	"MarkMonitor Inc."
     expiration_date	"2020-10-20 04:00:00"
        name_servers	"set(['ns2.google.com\r', 'ns1.google.com\r', 'ns4.google.com\r', 'ns3.google.com\r'])"

$ python2 test.py test.taxi
Domain: test.taxi, host: None
        last_updated	"2019-12-22 11:16:30"
                name	"test.taxi"
       registrant_cc	"nl"
       creation_date	"2016-11-28 15:10:31"
           registrar	"Metaregistrar BV"
     expiration_date	"2020-11-28 15:10:31"
        name_servers	"set(['ns1.metaregistrar.nl\r', 'ns2.metaregistrar.nl\r'])"
```

**Comment by k0ste** [comment]
Sorry, but I can't reproduce this issue on master. I was try python 3.8.1 and 2.7.17, with whois 5.5.3.

```
$ python2 test.py google.org
--------------------------------------------------------------------------------
Domain: google.org, host: None
        last_updated	"2019-09-18 09:31:16"
                name	"google.org"
       registrant_cc	"us"
       creation_date	"1998-10-21 04:00:00"
           registrar	"MarkMonitor Inc."
     expiration_date	"2020-10-20 04:00:00"
        name_servers	"set(['ns3.google.com', 'ns4.google.com', 'ns1.google.com', 'ns2.google.com'])"
$ python2 test.py test.taxi
--------------------------------------------------------------------------------
Domain: test.taxi, host: None
        last_updated	"2019-12-22 11:16:30"
                name	"test.taxi"
       registrant_cc	"nl"
       creation_date	"2016-11-28 15:10:31"
           registrar	"Metaregistrar BV"
     expiration_date	"2020-11-28 15:10:31"
        name_servers	"set(['ns1.metaregistrar.nl', 'ns2.metaregistrar.nl'])"
```

**Comment by tierpod** [comment]
I see, I have another whois version installed:

```
# whois --version
jwhois version 4.0, Copyright (C) 1999-2007  Free Software Foundation, Inc.
This program is free software with ABSOLUTELY NO WARRANTY; you may
redistribute it under the terms of the GNU General Public License.
```

I tested with ```whois Version 5.1.1.``` and there is no "\r" symbol. Interesting, maybe they used different end of line symbol.

Anyway, if you think that this additional strip() can break something, I will remove this 18cdcc7 commit.

**Comment by tierpod** [comment]
Yes, I dumped raw data from whois and jwois output and found the difference:

```
whois: ASCII text, with very long lines
jwhois: ASCII text, with very long lines, with CRLF, LF line terminators
```

**Comment by k0ste** [comment]
Good to hear that we clarified the core issue.

**Pull request merged**
