### PR TITLE
Additional Asian countries and CC detections

### PR DESCRIPTION
**Pull request by tenninjas**
Added handling for .cn .hk and .kr TLD's
Additionally improved location CC detection for .uk and .pl

### CODE REVIEW

**Comment by tenninjas** [comment]
I've checked that the hk & kr additions also work correctly for second level delegations (i.e.: .com.hk and .co.kr). Parsing is only in english, since the rest of the library also behaves this way.

**Comment by tenninjas** [comment]
There could probably be smarter detection for the return encoding, but I've only encountered problem cases where servers return ISO-8859-1, nothing else in practice. So better detection may not be worth the cost.

**Comment by gen1us2k** [comment]
Merged. Can you give some examples with ISO-8859-1 encoding?

**Comment by tenninjas** [comment]
internic.net does this - which ordinarily doesn't trigger anything, but if there are non-latin characters you will see output symbols and trigger this error. For example try:
$ whois jqw.com

**Comment by tenninjas** [comment]
Ironically the field with the invalid characters in this example is not even a field worth capturing (Reseller). However the error still presents and causes breakage.

**Comment by tenninjas** [comment]
I'm not sure your contribution guidelines, but I may be making several more fixes as I work with this library in the very-near future. Do you prefer I make pull requests after any change set, or would it be better to wait longer?

**Comment by gen1us2k** [comment]
You can send pull request, as you want.
You can open issues.
You can help me to make this library more better and helpful
You're welcome.

**Comment by tenninjas** [comment]
Ok; thank you. I am glad to help.

**Pull request merged**
