### PR TITLE
Remove .fm and add .bo support

### PR DESCRIPTION
**Pull request by tenninjas**
The .fm TLD no longer runs a whois server, so any query attempts will cause an exception. Also added support for .bo

### CODE REVIEW

**Comment by gen1us2k** [comment]
fm domains registrated on godaddy works fine. So not remove it please.
Open issue for exception please.

**Comment by tenninjas** [comment]
Can you give an example of this? I have tested a large number of .fm domains with no success at all. All .fm domains now return that whois must go through a web UI. Please let me know an example of a working domain with whois protocol

**Comment by gen1us2k** [comment]
namba.fm for example

**Comment by tenninjas** [comment]
Alright, will close this and create a separate full for .bo

**Comment by gen1us2k** [comment]
OK

2015-04-20 20:31 GMT+06:00 tenninjas notifications@github.com:

**Pull request closed without merging**
